//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papeleria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbModels : DbContext
    {
        public DbModels()
            : base("name=DbModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Departamentos> Departamentos { get; set; }
        public DbSet<Empleados> Empleados { get; set; }
        public DbSet<Evaluaciones_Desempeno> Evaluaciones_Desempeno { get; set; }
        public DbSet<Horarios> Horarios { get; set; }
        public DbSet<Puestos> Puestos { get; set; }
    }
}
